import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "98.css";
import React from "react"
import Link from 'next/link';

export default function Home() {

  return (

    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer className='title-bar' style={{ position: "absolute", bottom: 0, width: "100%" }}>
        <Link href="/test"><button className='button'>Test Page</button></Link>

      </footer>
    </div>

  )
}
